#!/bin/bash
# Osum-Konfiguration fuer busybox: nur was die Runde verlangt.
set -e
cd /root/fremdland-tmp/busybox
make allnoconfig >/dev/null 2>&1
CFG=.config
on() { sed -i "s/^# $1 is not set/$1=y/; " $CFG; grep -q "^$1=y" $CFG || echo "$1=y" >> $CFG; }
off() { sed -i "s/^$1=y/# $1 is not set/" $CFG; }

# statisch, kein NLS, kein Debug
on CONFIG_STATIC
on CONFIG_FEATURE_PREFER_APPLETS
on CONFIG_LONG_OPTS
on CONFIG_SHOW_USAGE
# Shell
on CONFIG_ASH
on CONFIG_SH_IS_ASH
on CONFIG_ASH_OPTIMIZE_FOR_SIZE
on CONFIG_ASH_INTERNAL_GLOB
on CONFIG_ASH_ALIAS
on CONFIG_ASH_ECHO
on CONFIG_ASH_TEST
on CONFIG_ASH_PRINTF
on CONFIG_ASH_GETOPTS
on CONFIG_ASH_CMDCMD
# coreutils der Abnahme
for a in CAT LS ECHO WC SORT HEAD TAIL CP MV RM MKDIR DATE ENV PWD TRUE FALSE \
         TEST SLEEP TOUCH SEQ BASENAME DIRNAME CUT TR UNAME YES PRINTF EXPR OD; do
  on CONFIG_$a
done
on CONFIG_GREP
on CONFIG_SED
on CONFIG_AWK
on CONFIG_FIND
on CONFIG_FEATURE_LS_FILETYPES
on CONFIG_FEATURE_LS_RECURSIVE
on CONFIG_FEATURE_LS_SORTFILES
on CONFIG_FEATURE_LS_TIMESTAMPS
on CONFIG_FEATURE_LS_WIDTH
on CONFIG_FEATURE_SORT_BIG
on CONFIG_FEATURE_FIND_TYPE
on CONFIG_FEATURE_FIND_NAME
on CONFIG_FEATURE_GREP_EGREP_ALIAS
on CONFIG_FEATURE_SEAMLESS_Z 2>/dev/null || true
off CONFIG_FEATURE_SEAMLESS_Z
off CONFIG_FEATURE_SEAMLESS_GZ
off CONFIG_FEATURE_SEAMLESS_BZ2
off CONFIG_FEATURE_SEAMLESS_LZMA
off CONFIG_FEATURE_SEAMLESS_XZ
off CONFIG_SELINUX
off CONFIG_PAM
off CONFIG_FEATURE_UTMP
off CONFIG_FEATURE_WTMP
off CONFIG_LOCALE_SUPPORT
off CONFIG_UNICODE_SUPPORT
off CONFIG_FEATURE_SYSLOG
off CONFIG_FEATURE_SUID
off CONFIG_FEATURE_HAVE_RPC
off CONFIG_FEATURE_MOUNT_NFS
off CONFIG_FEATURE_INETD_RPC
off CONFIG_INSTALL_NO_USR
yes '' | make oldconfig >/dev/null 2>&1
grep -c '^CONFIG_.*=y' $CFG
