#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
"""tools/pdf/gentab.py -- writes lib/pdfread/pdftab.fi: the data tables of the
PDF reader (the 14 standard fonts' widths, the base encodings, Adobe's glyph
list). Source: reportlab's copies of Adobe's AFM data and glyph list.

    python3 tools/pdf/gentab.py > lib/pdfread/pdftab.fi
"""
import sys
from reportlab.pdfbase import _fontdata as fd
from reportlab.pdfbase._fontdata_enc_winansi import WinAnsiEncoding
from reportlab.pdfbase._fontdata_enc_macroman import MacRomanEncoding
from reportlab.pdfbase._fontdata_enc_standard import StandardEncoding
from reportlab.pdfbase._glyphlist import _glyphname2unicode as agl

def uni_of(name):
    if name is None:
        return 0
    if name in agl:
        return agl[name]
    return 0

def widths(font, enc):
    g = fd.widthsByFontGlyph[font]
    out = []
    for c in range(256):
        n = enc[c]
        out.append(int(g.get(n, 0)) if n else 0)
    return out

def arr(name, vals, ty="u16"):
    rows = []
    for i in range(0, len(vals), 16):
        rows.append("    " + ", ".join(str(v) for v in vals[i:i+16]))
    return "static mut %s: [%s; %d] = [\n%s,\n]\n" % (name, ty, len(vals), ",\n".join(rows))

out = []
out.append("// SPDX-License-Identifier: GPL-2.0-only\n// lib/pdfread/pdftab.fi -- GENERATED by tools/pdf/gentab.py. Do not edit.\n"
           "// The widths of the 14 standard fonts (WinAnsi order), the base encodings\n"
           "// (code -> Unicode) and Adobe's glyph list (name -> Unicode).\n\n")
out.append("export { std_width, base_uni, agl_lookup }\n\n")
fonts = [("W_HELV", "Helvetica"), ("W_HELVB", "Helvetica-Bold"), ("W_TIMES", "Times-Roman"),
         ("W_TIMESB", "Times-Bold"), ("W_TIMESI", "Times-Italic"), ("W_TIMESBI", "Times-BoldItalic")]
for var, f in fonts:
    out.append(arr(var, widths(f, WinAnsiEncoding)))
out.append(arr("U_WIN", [uni_of(n) for n in WinAnsiEncoding]))
out.append(arr("U_MAC", [uni_of(n) for n in MacRomanEncoding]))
out.append(arr("U_STD", [uni_of(n) for n in StandardEncoding]))
# the glyph list as "name=hex\n" lines, sorted; only BMP, only the first code point of a sequence
ent = []
for name, u in agl.items():
    if isinstance(u, int) and 0 < u < 0x10000 and len(name) <= 24:
        ent.append("%s=%x\n" % (name, u))
ent.sort()
blob = "".join(ent)
assert '"' not in blob and "\\" not in blob
out.append('static mut AGL: [u8; %d] = "%s\\0"\n\n' % (len(blob.encode()) + 1, blob.replace("\n", "\\n")))
out.append('''
// width of `code` in a standard font: kind 0 Helvetica, 1 Helvetica-Bold, 2 Times,
// 3 Times-Bold, 4 Times-Italic, 5 Times-BoldItalic, 6 Courier; 0 = not known
fn std_width(kind: u32, code: u32) -> u32 {
    if code > 255 {
        return 0
    }
    if kind == 6 {
        return 600
    }
    if kind == 0 {
        return W_HELV[code as usize] as u32
    }
    if kind == 1 {
        return W_HELVB[code as usize] as u32
    }
    if kind == 2 {
        return W_TIMES[code as usize] as u32
    }
    if kind == 3 {
        return W_TIMESB[code as usize] as u32
    }
    if kind == 4 {
        return W_TIMESI[code as usize] as u32
    }
    return W_TIMESBI[code as usize] as u32
}

// enc 0 WinAnsi, 1 MacRoman, 2 Standard
fn base_uni(enc: u32, code: u32) -> u32 {
    if code > 255 {
        return 0
    }
    if enc == 1 {
        return U_MAC[code as usize] as u32
    }
    if enc == 2 {
        return U_STD[code as usize] as u32
    }
    return U_WIN[code as usize] as u32
}

// The Unicode of a glyph name: the list, then uniXXXX / uXXXX; 0 = unknown
fn agl_lookup(p: u64, n: u64) -> u32 {
    if n == 0 || n > 24 {
        return 0
    }
    let base: u64 = (&AGL[0 as usize]) as u64
    var i: u64 = 0
    let total: u64 = ''' + str(len(blob.encode())) + ''' as u64
    while i < total {
        // compare the name against the line at i
        var j: u64 = 0
        var same: bool = true
        while j < n {
            if (*((base + i + j) as *mut u8)) != (*((p + j) as *mut u8)) {
                same = false
                j = n
            } else {
                j = j + 1
            }
        }
        if same && (*((base + i + n) as *mut u8)) == 61 {
            var v: u32 = 0
            var k: u64 = i + n + 1
            while (*((base + k) as *mut u8)) != 10 {
                let c: u32 = (*((base + k) as *mut u8)) as u32
                var h: u32 = 0
                if c >= 48 && c <= 57 {
                    h = c - 48
                } else {
                    h = c - 87
                }
                v = v * 16 + h
                k = k + 1
            }
            return v
        }
        // next line
        while i < total && (*((base + i) as *mut u8)) != 10 {
            i = i + 1
        }
        i = i + 1
    }
    // uniXXXX / uXXXX
    var off: u64 = 0
    if n >= 7 && (*(p as *mut u8)) == 117 && (*((p + 1) as *mut u8)) == 110 && (*((p + 2) as *mut u8)) == 105 {
        off = 3
    } else if n >= 5 && (*(p as *mut u8)) == 117 {
        off = 1
    }
    if off > 0 {
        var v2: u32 = 0
        var m: u64 = off
        while m < n && m < off + 4 {
            let c2: u32 = (*((p + m) as *mut u8)) as u32
            var h2: u32 = 99
            if c2 >= 48 && c2 <= 57 {
                h2 = c2 - 48
            } else if c2 >= 65 && c2 <= 70 {
                h2 = c2 - 55
            } else if c2 >= 97 && c2 <= 102 {
                h2 = c2 - 87
            }
            if h2 == 99 {
                return 0
            }
            v2 = v2 * 16 + h2
            m = m + 1
        }
        return v2
    }
    return 0
}
''')
sys.stdout.write("".join(out))
